### ISSUE TITLE
Support for publishing to multiple channels

### ISSUE THREAD

**Issue by smtchahal** [fanout/php-gripcontrol#6]
Is there a way to publish to multiple channels at once, using a single request, rather than making a separate request for each publish with this library?

I know it's possible using a raw POST request to Pushpin's control API by specifying multiple `"items"` in the input JSON.

I'd make a PR, but I'm not sure if this is not already possible using the library. If it is, maybe we could document this in the readme?

**Comment by jkarneges** [comment]
Sending multiple messages to Pushpin in a single request is possible when using async publishing, although not much control is provided. Basically, messages are queued in the background and a single publishing thread reads potentially multiple messages from the queue before sending. This leads to an efficient batching effect if you send lots of messages, although if the thread is idle then the next message usually goes out immediately on its own.

It might be possible to send multiple messages on the same request after idle by calling `publish_async` fast enough, e.g. by preparing all of the messages before sending.

If you want more control, I'm open to ideas. By the way, the actual publishing is provided by [pubcontrol](https://github.com/fanout/php-pubcontrol).

**Comment by smtchahal** [comment]
@jkarneges My use case requires the use of synchronous publishing, since my backend is a PHP web server, [which does not support `pthreads`](http://php.net/manual/en/intro.pthreads.php), which is needed for asynchronous publishing.

I simply want to be able to synchronously publish the same message to multiple channels without having to fire multiple requests to Pushpin's control API.

It could be implemented in the existing `PubControl->publish` method, or as a separate method that works exactly the same as `PubControl->publish`, except it takes an array of channels as its first parameter.

From my (naive) testing, it requires changes to `pubcontrol.php` and `pubcontrolclient.php`, but obviously I didn't consider anything else that might also need to change, since my only use case is WebSocket-over-http.

Could something like this be implemented in the library?

**Comment by jkarneges** [comment]
Yes, I think this is reasonable and the needed changes probably wouldn't be very large either. I've filed an [issue](https://github.com/fanout/php-pubcontrol/issues/5) on php-pubcontrol. Further discussion should happen over there.
